version: 2
updates:
  # - package-ecosystem: "pip"
  #   directory: "/dependencies"
  #   schedule:
  #     interval: "daily"
  #   target-branch: "master"
  - package-ecosystem: "pip"
    directory: "/setup.py"
    schedule:
      interval: "daily"
    target-branch: "master"
